spring:
  rabbitmq:
    host: server
    port: 5672
    username: guest
    password: guest
    virtual-host: /rabbitmq
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true
