server:
  port: 8084
spring:
  application:
    name: spring-boot-session
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: localhost
    port: 6379
    database: 0