server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: minio
  profiles:
    active: default
    include:
      - minio
      - mybatis-plus
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://server:3306/spring_boot
    username: root
    password: root
