server:
  port: 8080
spring:
  application:
    name: spring-boot-session-jdbc
  session:
    store-type: jdbc
    timeout: 1800
  datasource:
    url: jdbc:mysql://localhost:3306/spring_session
    username: root
    password: root