version: "3.9"

services:

  nginx:
    image: nginx
    environment:
      - NGINX_HOST=server
      - NGINX_PORT=80
    ports:
      - "80:80"
    restart: always

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always

  adminer:
    image: adminer
    ports:
      - "3307:8080"
    restart: always

  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    restart: always

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    ports:
      - "27018:8081"
    restart: always

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
