version: "3.9"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=server
      - NGINX_PORT=80
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    ports:
      - 6379:6379

  mongodb:
    image: mongo
    ports:
      - 27017:27017