version: "3.9"

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=server
      - NGINX_PORT=80

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "3307:8080"

  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    restart: always

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  minio:
    restart: always
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin