server:
  port: 8084
spring:
  application:
    name: spring-boot-web
  web:
    resources:
      static-locations: classpath:static/
  mvc:
    static-path-pattern: /**
    view:
      prefix: /html/
      suffix: .html