version: "3.9"

services:

  nginx:
    image: nginx
    environment:
      - NGINX_HOST=server
      - NGINX_PORT=80
    ports:
      - "80:80"
    restart: always

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    restart: always

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

  elasticsearch:
    image: elasticsearch:8.2.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  kibana:
    image: kibana:8.2.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always
