spring:
  datasource:
    druid:
      filters: stat,wall
      filter:
        stat.log-slow-sql: true
        stat.slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
          enabled: true
          url-pattern: /druid/*

