server:
  port: 8084
spring:
  application:
    name: spring-boot-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: root
  thymeleaf:
    cache: false