server:
  port: 8080
  servlet:
    context-path: /admin-server
spring:
  application:
    name: admin-server
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
  profiles:
    active: default
