spring:
  application:
    name: druid
  profiles:
    active: default
    include:
      - druid
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://server:3306/spring_boot
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
