server:
  port: 8081
spring:
  application:
    name: spring-boot-admin-client
  boot:
    admin:
      client:
        url: http://localhost:8084
management:
  endpoints:
    web:
      exposure:
        include: '*'